# default.yml controls global settings and policies/queries that run on all hosts ("All teams").

labels:
  - path: ./lib/all/labels/global-labels.yml
policies:
queries:
agent_options:
  command_line_flags:
    es_fim_enable_open_events: true
    disable_endpointsecurity_fim: true
    disable_endpointsecurity: false
    host_identifier: ephemeral
    es_fim_enable_open_events: true   
controls:
org_settings:
  fleet_desktop:
    transparency_url: https://catoftheday.com
  host_expiry_settings:
    host_expiry_enabled: true
    host_expiry_window: 30
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: Detroit GitOps
  webhook_settings:
    activities_webhook:
      enable_activities_webhook: true
      destination_url: https://webhook.site/946f9dfb-ebae-43ef-809e-d5cb707ad20a
  secrets:
    - secret: "REPLACE_WITH_ENVIRONMENT_VARIABLE"
